# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xn9KRHLpwltnDFRMfcDOcrWua4Mk4zUT
"""

import pandas as pd
import numpy as np

# ---------------------------------------------------------
# 1. SIMULATE BOUTIQUE FITNESS MEMBER DATA
# ---------------------------------------------------------
# Simulating 2,000 members for a boutique fitness studio (e.g., Orangetheory style)
np.random.seed(42)
n_members = 2000

data = {
    'member_id': range(1000, 1000 + n_members),
    'months_active': np.random.randint(1, 36, n_members),
    'avg_classes_per_month': np.random.normal(6, 2, n_members).clip(0, 20),
    'late_cancellation_rate': np.random.uniform(0.01, 0.30, n_members),
    'bought_wearable_tech': np.random.choice([0, 1], n_members, p=[0.6, 0.4]), # Did they buy a heart rate monitor?
}

df = pd.DataFrame(data)

# Injecting logical churn behavior: High late cancellations and low attendance = high churn risk
risk_score = (df['late_cancellation_rate'] * 10) - df['avg_classes_per_month']
df['churned_last_30_days'] = np.where(risk_score > -2, np.random.choice([0, 1], n_members, p=[0.3, 0.7]), 0)

# ---------------------------------------------------------
# 2. DETERMINISTIC BREAK-EVEN & CLV MODEL
# ---------------------------------------------------------
# Business Constants (Estimates for Boutique Fitness)
CAC = 150.00          # Customer Acquisition Cost (Marketing, free first class)
MONTHLY_FEE = 169.00  # Unlimited Tier
MARGIN = 0.35         # Studio operating margin per membership dollar

# Calculate Revenue and CLV
df['total_revenue'] = df['months_active'] * MONTHLY_FEE
df['lifetime_margin'] = df['total_revenue'] * MARGIN

# Deterministic Break-Even: Does their lifetime margin cover the cost to acquire them?
df['is_profitable'] = df['lifetime_margin'] >= CAC
months_to_breakeven = CAC / (MONTHLY_FEE * MARGIN)

print(f"--- BOUTIQUE FITNESS UNIT ECONOMICS ---")
print(f"Deterministic Break-Even Point: {months_to_breakeven:.1f} months\n")

# ---------------------------------------------------------
# 3. LOYALTY & EXPERIMENTATION INSIGHTS
# ---------------------------------------------------------
# Let's see how buying the wearable tech impacts CLV (Arash's dunnhumby background)
clv_by_tech = df.groupby('bought_wearable_tech')['months_active'].mean().reset_index()
clv_by_tech.columns = ['Bought Tech', 'Avg Months Retained']

print("--- LOYALTY INSIGHT: WEARABLE TECH IMPACT ---")
print(clv_by_tech.to_string(index=False))
print("\nInsight: Members who buy the studio's wearable tech stay longer. This is a clear personalization hook for onboarding.")

# Identifying the "Saveable" Cohort for an Experiment
saveable = df[(df['avg_classes_per_month'] < 4) & (df['churned_last_30_days'] == 0) & (df['months_active'] > 3)]
print(f"\n--- EXPERIMENTATION TARGET ---")
print(f"Found {len(saveable)} active members showing pre-churn behavior (attending < 4x/month).")
print("Next Best Action: Launch A/B test with automated SMS win-back offer to this specific cohort.")